// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYssexuXyUy5rekL4cQf6Xo3qE5MCUZwc',
    appId: '1:58963407730:android:6404ffc400c62c1f7a23eb',
    messagingSenderId: '58963407730',
    projectId: 'peace-8cae8',
    storageBucket: 'peace-8cae8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEWyZLU6zduVO7M43mv3bkJ3aYShtYXGI',
    appId: '1:58963407730:ios:1a81b9a2e73185757a23eb',
    messagingSenderId: '58963407730',
    projectId: 'peace-8cae8',
    storageBucket: 'peace-8cae8.appspot.com',
    androidClientId: '58963407730-b9b23urndjqt5qkk9r58uht6ktcnd5kl.apps.googleusercontent.com',
    iosClientId: '58963407730-v3plts8th30prep06nppjfcanmufs1jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.peace',
  );
}
